version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - laravelnet
    volumes:
      - esdata:/usr/share/elasticsearch/data

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-laravel
    container_name: foodApi
    working_dir: /var/www/html
    volumes:
      - C:/xampp/htdocs/jadeveloper/products-parse-truckPag/food-api-truckpag:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - laravelnet
    depends_on:
      - elasticsearch

volumes:
  esdata:

networks:
  laravelnet:
    driver: bridge
